::: {.content-visible unless-meta="in.article"}
### Exploratory ARIMA modelling
:::

Accounting for the presence of weekly and yearly seasonality, autoregressive integrated moving average (ARIMA) model was performed on weekly series. Weekly series was selected over daily series because it represents the population dynamic better. The daily series was highly noisy due to differences in the amount of patients claiming their medication, where it peaked on Monday and at its lowest on Saturday. On the other hand, weekly series was selected over monthly series because it preserves the data point while still capturing the seasonal pattern. ARIMA model was fitted using Hyndman-Khandakar algorithm to minimize Akaike Information Criterion (AIC) with a forward-backward stepwise selection. AIC was preferred instead of Bayesian Information Criterion (BIC) since BIC penalizes the number of parameters. However, since the main purpose of Hyndman-Khandakar algorithm is to minimize information criterion, it does not necessarily find the generalizable parameters in the data. In the presence of mixed seasonality and complex periodic patterns, the algorithm might fail to capture the right parameters. As such, an exploratory ARIMA modelling was *not* aimed to find a parsimonious model; rather, it was intended to confirm the presence of simple seasonal pattern.
