::: {.content-visible unless-meta="in.article"}
### Source of data
:::

All data in this study originated from the University of Groningen IADB.nl, a dynamic pharmacy database containing prescription records since 1994. The database covers approximately 128 community pharmacies serving over one million patients and was accessed on the 20^th^ of September 2023. In the Netherlands, the primary route of obtaining prescription medications is through community pharmacies, as physicians issue prescriptions that are almost exclusively dispensed in these settings. Consequently, the database provides a comprehensive longitudinal record for each individual, supported by high patient-pharmacy commitment. All patients are recorded in the database, irrespective of health care insurance, where the prescription rates, age, and gender are generalizable to represent the Netherlands [@Visser2013]. Each record includes the dispensing date, quantity, dose regimen, number of days prescribed, prescribing physician, and the corresponding Anatomical Therapeutic Chemical (ATC) code. Medication dispensed during hospitalization and over-the-counter drugs are not captured, but prescription medication records in community pharmacies are otherwise complete.

This analysis includes daily drug dispensing record from a static cohort of adults aged 18 to 65 years and prescribed anxiolytics or antidepressants at least once in the period 2018-2022. For this study, only a subset of the database was used to construct the DPN: anonymized patient identifiers, age, prescription start and end dates, and ATC codes. No additional individual-level data were included to align with general data minimization requirements. Other demographic or clinical information available in the database was not extracted.
