---
title: >
  Supplementary: A temporal network analysis of drug co-prescription around antidepressants and anxiolytics uses in the Netherlands from 2018 to 2022

format:
  pdf:
    keep-tex: true
    include-in-header:
      - file: _header.tex
      - text: |
          \renewcommand*{\thesection}{S\arabic{section}}
    output-file: iadb-network-analysis-supplementary.pdf
    number-sections: true
    number-depth: 3
    geometry:
      - inner=2cm
      - outer=3cm
      - top=2cm
      - bottom=2.5cm

metadata-files:
  - _author.yml
  - _knitr-bib.yml

in:
  article: true
---

```{r}

pkgs <- c("targets", "magrittr")
pkgs_load <- sapply(pkgs, library, character.only = TRUE)
options(digits = 2)

```

# Methods

## Decomposition with singular spectrum analysis

{{< include exec-summary/_spectral.qmd >}}

\uselandscape

# Results

## Cyclical patterns on de-trended data

```{r fig-period-day}
#| fig-width: 14
#| fig-height: 8
#| fig-cap: Daily cyclical pattern captured on a de-trended data

tar_read(plt_period_day)[[1]]

```

\pagebreak

## Daily ACF and PACF plots

```{r fig-season-day}
#| fig-width: 14
#| fig-height: 8
#| fig-cap: Daily cyclical pattern captured on a de-trended data

tar_read(plt_acf_day)[[4]]
tar_read(plt_pacf_day)[[4]]

```

\pagebreak

## Weekly ACF and PACF plots

```{r fig-season-week}
#| fig-width: 14
#| fig-height: 8
#| fig-cap: Daily cyclical pattern captured on a de-trended data

tar_read(plt_acf_week)[[4]]
tar_read(plt_pacf_week)[[4]]

```

## Time-series decomposition of medication dispensing records

```{r}
#| fig-width: 14
#| fig-height: 8
#| fig-cap: Reconstructed time series data using the SSA-based approach

tar_read(plt_dot_recon_n_claim)
tar_read(plt_dot_recon_eigen)

```

\normalpapersize

```{r tbl-trend}
#| tbl-cap: Trend of medication uses alongside its measure of relative importance

prettyRound <- function(x, ...) {
  x %<>% round(...) %>% {ifelse(. == 0, "<0.001", as.character(.))}
}

fnote <- "The statistics were obtained from Mann-Kendall trend test, where positive result signifies a positive slope"

tar_read(decom_ssa) %>%
  subset(.$component %in% c("Original", "Trend") & .$metric != "claim2patient") %>%
  tibble::tibble() %>%
  dplyr::group_by(metric, group, component) %>%
  dplyr::group_modify(~trend::mk.test(.x$value) %>% broom::tidy()) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    "Mann-Kendall" = sprintf(
      "%s (p %s)", prettyRound(statistic, 2), prettyRound(p.value, 3)
    )
  ) %>%
  subset(select = -c(statistic:alternative)) %>%
  tidyr::pivot_wider(names_from = metric, values_from = `Mann-Kendall`) %>%
  tidyr::pivot_wider(names_from = component, values_from = eigen:n_claim) %>%
  set_colnames(c("ATC Group", rep(c("Original", "Trend"), 2))) %>%
  knitr::kable(longtable = TRUE, booktabs = TRUE) %>%
  kableExtra::kable_styling(latex_options = "repeat_header") %>%
  kableExtra::add_header_above(c(" " = 1, "Eigenvector Centrality" = 2, "Prescription Dispensing" = 2)) %>%
  kableExtra::add_footnote(fnote, notation = "none")

```

```{r}
#| fig-width: 16
#| fig-height: 9
#| fig-pos: H
#| fig-cap: Time-series decomposition using singular spectrum analysis-based approach
#| eval: FALSE

tar_read(plt_ssa_recon_n_claim)[[1]]
tar_read(plt_ssa_recon_n_claim)[[2]]
tar_read(plt_ssa_recon_n_claim)[[3]]
tar_read(plt_ssa_recon_n_claim)[[4]]
tar_read(plt_ssa_recon_n_claim)[[5]]
tar_read(plt_ssa_recon_n_claim)[[6]]
tar_read(plt_ssa_recon_n_claim)[[7]]
tar_read(plt_ssa_recon_n_claim)[[8]]
tar_read(plt_ssa_recon_n_claim)[[9]]
tar_read(plt_ssa_recon_n_claim)[[10]]
tar_read(plt_ssa_recon_n_claim)[[11]]
tar_read(plt_ssa_recon_n_claim)[[12]]
tar_read(plt_ssa_recon_n_claim)[[13]]
tar_read(plt_ssa_recon_n_claim)[[14]]
tar_read(plt_ssa_recon_n_claim)[[15]]
tar_read(plt_ssa_recon_n_claim)[[16]]
tar_read(plt_ssa_recon_n_claim)[[18]]
tar_read(plt_ssa_recon_n_claim)[[19]]
tar_read(plt_ssa_recon_n_claim)[[20]]
tar_read(plt_ssa_recon_n_claim)[[21]]
tar_read(plt_ssa_recon_n_claim)[[22]]
tar_read(plt_ssa_recon_n_claim)[[23]]
tar_read(plt_ssa_recon_n_claim)[[24]]

tar_read(plt_ssa_recon_eigen)[[1]]
tar_read(plt_ssa_recon_eigen)[[2]]
tar_read(plt_ssa_recon_eigen)[[3]]
tar_read(plt_ssa_recon_eigen)[[4]]
tar_read(plt_ssa_recon_eigen)[[5]]
tar_read(plt_ssa_recon_eigen)[[6]]
tar_read(plt_ssa_recon_eigen)[[7]]
tar_read(plt_ssa_recon_eigen)[[8]]
tar_read(plt_ssa_recon_eigen)[[9]]
tar_read(plt_ssa_recon_eigen)[[10]]
tar_read(plt_ssa_recon_eigen)[[11]]
tar_read(plt_ssa_recon_eigen)[[12]]
tar_read(plt_ssa_recon_eigen)[[13]]
tar_read(plt_ssa_recon_eigen)[[14]]
tar_read(plt_ssa_recon_eigen)[[15]]
tar_read(plt_ssa_recon_eigen)[[16]]
tar_read(plt_ssa_recon_eigen)[[17]]
tar_read(plt_ssa_recon_eigen)[[18]]
tar_read(plt_ssa_recon_eigen)[[19]]
tar_read(plt_ssa_recon_eigen)[[20]]
tar_read(plt_ssa_recon_eigen)[[21]]
tar_read(plt_ssa_recon_eigen)[[22]]
tar_read(plt_ssa_recon_eigen)[[23]]
tar_read(plt_ssa_recon_eigen)[[24]]

```

# References {-}
